# Generated by Django 3.0 on 2020-01-19 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200118_1805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Searcher',
            new_name='Poster',
        ),
    ]
