# Generated by Django 3.0 on 2020-01-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20200118_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.IntegerField(default=5)),
                ('message_content', models.CharField(max_length=250)),
            ],
        ),
    ]
