# Generated by Django 3.0 on 2020-01-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='worker_id',
            field=models.IntegerField(default=0),
        ),
    ]
